version: '3.8'

services:
    app:
        build:
            context: .
        container_name: balance_app
        volumes:
            - .:/var/www
        ports:
            - "9000:9000"
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        container_name: balance_nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: postgres:15
        container_name: balance_pgsql
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: laravel
            POSTGRES_USER: laravel
            POSTGRES_PASSWORD: secret
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - laravel

networks:
    laravel:

volumes:
    pgdata:
